// =====================================================
// System-wide constants
// =====================================================

export const APP_NAME = "HRMS Portal";
export const APP_NAME_AR = "بوابة الموارد البشرية";
export const DEFAULT_LOCALE = "ar";
export const SUPPORTED_LOCALES = ["ar", "en"] as const;
export const DEFAULT_THEME = "light";

export const ROLES = {
  EMPLOYEE: "EMPLOYEE",
  MANAGER: "MANAGER",
  HR_OFFICER: "HR_OFFICER",
  HR_MANAGER: "HR_MANAGER",
  PAYROLL_OFFICER: "PAYROLL_OFFICER",
  SYSTEM_ADMIN: "SYSTEM_ADMIN",
} as const;

export const ROLE_LEVELS = {
  EMPLOYEE: 1,
  MANAGER: 2,
  HR_OFFICER: 3,
  PAYROLL_OFFICER: 3,
  HR_MANAGER: 4,
  SYSTEM_ADMIN: 5,
} as const;

// =====================================================
// Permission codes
// =====================================================

export const PERMISSIONS = {
  // Employees
  EMPLOYEES_VIEW: "employees.view",
  EMPLOYEES_CREATE: "employees.create",
  EMPLOYEES_UPDATE: "employees.update",
  EMPLOYEES_DELETE: "employees.delete",
  EMPLOYEES_EXPORT: "employees.export",

  // Departments
  DEPARTMENTS_VIEW: "departments.view",
  DEPARTMENTS_MANAGE: "departments.manage",

  // Positions
  POSITIONS_VIEW: "positions.view",
  POSITIONS_MANAGE: "positions.manage",

  // Attendance
  ATTENDANCE_VIEW_OWN: "attendance.view_own",
  ATTENDANCE_VIEW_TEAM: "attendance.view_team",
  ATTENDANCE_VIEW_ALL: "attendance.view_all",
  ATTENDANCE_MANAGE: "attendance.manage",
  ATTENDANCE_CHECK_IN: "attendance.check_in",

  // Leave
  LEAVE_REQUEST: "leave.request",
  LEAVE_VIEW_OWN: "leave.view_own",
  LEAVE_VIEW_TEAM: "leave.view_team",
  LEAVE_VIEW_ALL: "leave.view_all",
  LEAVE_APPROVE: "leave.approve",
  LEAVE_MANAGE: "leave.manage",

  // Payroll
  PAYROLL_VIEW_OWN: "payroll.view_own",
  PAYROLL_VIEW_ALL: "payroll.view_all",
  PAYROLL_PROCESS: "payroll.process",
  PAYROLL_APPROVE: "payroll.approve",
  PAYROLL_EXPORT: "payroll.export",
  PAYSLIPS_VIEW_OWN: "payslips.view_own",

  // Recruitment
  RECRUITMENT_VIEW: "recruitment.view",
  RECRUITMENT_MANAGE: "recruitment.manage",
  RECRUITMENT_INTERVIEW: "recruitment.interview",

  // Documents
  DOCUMENTS_VIEW_OWN: "documents.view_own",
  DOCUMENTS_VIEW_ALL: "documents.view_all",
  DOCUMENTS_MANAGE: "documents.manage",
  DOCUMENTS_UPLOAD: "documents.upload",

  // Notifications
  NOTIFICATIONS_VIEW: "notifications.view",
  NOTIFICATIONS_MANAGE: "notifications.manage",

  // Reports
  REPORTS_VIEW: "reports.view",
  REPORTS_EXPORT: "reports.export",

  // Settings
  SETTINGS_VIEW: "settings.view",
  SETTINGS_MANAGE: "settings.manage",

  // Audit
  AUDIT_VIEW: "audit.view",

  // Self-service
  PROFILE_VIEW_OWN: "profile.view_own",
  PROFILE_UPDATE_OWN: "profile.update_own",
  LOAN_REQUEST: "loan.request",
  EXPENSE_CLAIM: "expense.claim",
  OVERTIME_REQUEST: "overtime.request",
  SALARY_CERTIFICATE_REQUEST: "salary_certificate.request",
} as const;

// =====================================================
// Role -> Permissions mapping (for seeding)
// =====================================================

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  EMPLOYEE: [
    PERMISSIONS.ATTENDANCE_VIEW_OWN,
    PERMISSIONS.ATTENDANCE_CHECK_IN,
    PERMISSIONS.LEAVE_REQUEST,
    PERMISSIONS.LEAVE_VIEW_OWN,
    PERMISSIONS.PAYROLL_VIEW_OWN,
    PERMISSIONS.PAYSLIPS_VIEW_OWN,
    PERMISSIONS.DOCUMENTS_VIEW_OWN,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.PROFILE_VIEW_OWN,
    PERMISSIONS.PROFILE_UPDATE_OWN,
    PERMISSIONS.LOAN_REQUEST,
    PERMISSIONS.EXPENSE_CLAIM,
    PERMISSIONS.OVERTIME_REQUEST,
    PERMISSIONS.SALARY_CERTIFICATE_REQUEST,
  ],
  MANAGER: [
    PERMISSIONS.EMPLOYEES_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW_OWN,
    PERMISSIONS.ATTENDANCE_VIEW_TEAM,
    PERMISSIONS.ATTENDANCE_CHECK_IN,
    PERMISSIONS.LEAVE_REQUEST,
    PERMISSIONS.LEAVE_VIEW_OWN,
    PERMISSIONS.LEAVE_VIEW_TEAM,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.PAYROLL_VIEW_OWN,
    PERMISSIONS.PAYSLIPS_VIEW_OWN,
    PERMISSIONS.RECRUITMENT_VIEW,
    PERMISSIONS.RECRUITMENT_INTERVIEW,
    PERMISSIONS.DOCUMENTS_VIEW_OWN,
    PERMISSIONS.DOCUMENTS_VIEW_ALL,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.PROFILE_VIEW_OWN,
    PERMISSIONS.PROFILE_UPDATE_OWN,
    PERMISSIONS.LOAN_REQUEST,
    PERMISSIONS.EXPENSE_CLAIM,
    PERMISSIONS.OVERTIME_REQUEST,
    PERMISSIONS.SALARY_CERTIFICATE_REQUEST,
  ],
  HR_OFFICER: [
    PERMISSIONS.EMPLOYEES_VIEW,
    PERMISSIONS.EMPLOYEES_CREATE,
    PERMISSIONS.EMPLOYEES_UPDATE,
    PERMISSIONS.EMPLOYEES_EXPORT,
    PERMISSIONS.DEPARTMENTS_VIEW,
    PERMISSIONS.POSITIONS_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW_OWN,
    PERMISSIONS.ATTENDANCE_VIEW_ALL,
    PERMISSIONS.ATTENDANCE_CHECK_IN,
    PERMISSIONS.ATTENDANCE_MANAGE,
    PERMISSIONS.LEAVE_REQUEST,
    PERMISSIONS.LEAVE_VIEW_OWN,
    PERMISSIONS.LEAVE_VIEW_ALL,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.LEAVE_MANAGE,
    PERMISSIONS.PAYROLL_VIEW_OWN,
    PERMISSIONS.PAYSLIPS_VIEW_OWN,
    PERMISSIONS.RECRUITMENT_VIEW,
    PERMISSIONS.RECRUITMENT_MANAGE,
    PERMISSIONS.RECRUITMENT_INTERVIEW,
    PERMISSIONS.DOCUMENTS_VIEW_OWN,
    PERMISSIONS.DOCUMENTS_VIEW_ALL,
    PERMISSIONS.DOCUMENTS_MANAGE,
    PERMISSIONS.DOCUMENTS_UPLOAD,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.PROFILE_VIEW_OWN,
    PERMISSIONS.PROFILE_UPDATE_OWN,
    PERMISSIONS.LOAN_REQUEST,
    PERMISSIONS.EXPENSE_CLAIM,
    PERMISSIONS.OVERTIME_REQUEST,
    PERMISSIONS.SALARY_CERTIFICATE_REQUEST,
  ],
  PAYROLL_OFFICER: [
    PERMISSIONS.EMPLOYEES_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW_OWN,
    PERMISSIONS.ATTENDANCE_VIEW_ALL,
    PERMISSIONS.ATTENDANCE_CHECK_IN,
    PERMISSIONS.LEAVE_REQUEST,
    PERMISSIONS.LEAVE_VIEW_OWN,
    PERMISSIONS.LEAVE_VIEW_ALL,
    PERMISSIONS.PAYROLL_VIEW_OWN,
    PERMISSIONS.PAYROLL_VIEW_ALL,
    PERMISSIONS.PAYROLL_PROCESS,
    PERMISSIONS.PAYROLL_APPROVE,
    PERMISSIONS.PAYROLL_EXPORT,
    PERMISSIONS.PAYSLIPS_VIEW_OWN,
    PERMISSIONS.DOCUMENTS_VIEW_OWN,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.PROFILE_VIEW_OWN,
    PERMISSIONS.PROFILE_UPDATE_OWN,
    PERMISSIONS.LOAN_REQUEST,
    PERMISSIONS.EXPENSE_CLAIM,
    PERMISSIONS.OVERTIME_REQUEST,
    PERMISSIONS.SALARY_CERTIFICATE_REQUEST,
  ],
  HR_MANAGER: [
    PERMISSIONS.EMPLOYEES_VIEW,
    PERMISSIONS.EMPLOYEES_CREATE,
    PERMISSIONS.EMPLOYEES_UPDATE,
    PERMISSIONS.EMPLOYEES_DELETE,
    PERMISSIONS.EMPLOYEES_EXPORT,
    PERMISSIONS.DEPARTMENTS_VIEW,
    PERMISSIONS.DEPARTMENTS_MANAGE,
    PERMISSIONS.POSITIONS_VIEW,
    PERMISSIONS.POSITIONS_MANAGE,
    PERMISSIONS.ATTENDANCE_VIEW_OWN,
    PERMISSIONS.ATTENDANCE_VIEW_TEAM,
    PERMISSIONS.ATTENDANCE_VIEW_ALL,
    PERMISSIONS.ATTENDANCE_CHECK_IN,
    PERMISSIONS.ATTENDANCE_MANAGE,
    PERMISSIONS.LEAVE_REQUEST,
    PERMISSIONS.LEAVE_VIEW_OWN,
    PERMISSIONS.LEAVE_VIEW_TEAM,
    PERMISSIONS.LEAVE_VIEW_ALL,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.LEAVE_MANAGE,
    PERMISSIONS.PAYROLL_VIEW_ALL,
    PERMISSIONS.PAYROLL_APPROVE,
    PERMISSIONS.PAYROLL_EXPORT,
    PERMISSIONS.PAYSLIPS_VIEW_OWN,
    PERMISSIONS.RECRUITMENT_VIEW,
    PERMISSIONS.RECRUITMENT_MANAGE,
    PERMISSIONS.RECRUITMENT_INTERVIEW,
    PERMISSIONS.DOCUMENTS_VIEW_OWN,
    PERMISSIONS.DOCUMENTS_VIEW_ALL,
    PERMISSIONS.DOCUMENTS_MANAGE,
    PERMISSIONS.DOCUMENTS_UPLOAD,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.NOTIFICATIONS_MANAGE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.SETTINGS_MANAGE,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.PROFILE_VIEW_OWN,
    PERMISSIONS.PROFILE_UPDATE_OWN,
    PERMISSIONS.LOAN_REQUEST,
    PERMISSIONS.EXPENSE_CLAIM,
    PERMISSIONS.OVERTIME_REQUEST,
    PERMISSIONS.SALARY_CERTIFICATE_REQUEST,
  ],
  SYSTEM_ADMIN: Object.values(PERMISSIONS),
};

// =====================================================
// Pagination defaults
// =====================================================

export const DEFAULT_PAGE_SIZE = 10;
export const MAX_PAGE_SIZE = 100;

// =====================================================
// File upload constraints
// =====================================================

export const ALLOWED_IMAGE_TYPES = ["image/jpeg", "image/png", "image/webp"];
export const ALLOWED_DOCUMENT_TYPES = [
  "application/pdf",
  "application/msword",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "image/jpeg",
  "image/png",
];
export const MAX_FILE_SIZE = 10 * 1024 * 1024; // 10MB

// =====================================================
// Working days (Saudi week starts Sunday)
// =====================================================

export const SAUDI_WORKING_DAYS = [0, 1, 2, 3, 4]; // Sun-Thu
