// Translation strings - Arabic (default) and English
// Used by the i18n provider

export type Locale = "ar" | "en";

export const translations = {
  ar: {
    // App
    "app.name": "بوابة الموارد البشرية",
    "app.shortName": "HRMS",
    "app.tagline": "نظام إدارة الموارد البشرية والموظفين",

    // Common
    "common.welcome": "أهلاً وسهلاً",
    "common.dashboard": "لوحة التحكم",
    "common.profile": "الملف الشخصي",
    "common.settings": "الإعدادات",
    "common.notifications": "الإشعارات",
    "common.search": "بحث",
    "common.filter": "تصفية",
    "common.export": "تصدير",
    "common.import": "استيراد",
    "common.add": "إضافة",
    "common.edit": "تعديل",
    "common.delete": "حذف",
    "common.view": "عرض",
    "common.save": "حفظ",
    "common.cancel": "إلغاء",
    "common.confirm": "تأكيد",
    "common.close": "إغلاق",
    "common.back": "رجوع",
    "common.next": "التالي",
    "common.previous": "السابق",
    "common.submit": "إرسال",
    "common.loading": "جاري التحميل...",
    "common.noData": "لا توجد بيانات",
    "common.actions": "الإجراءات",
    "common.status": "الحالة",
    "common.date": "التاريخ",
    "common.name": "الاسم",
    "common.code": "الرمز",
    "common.description": "الوصف",
    "common.active": "نشط",
    "common.inactive": "غير نشط",
    "common.yes": "نعم",
    "common.no": "لا",
    "common.all": "الكل",
    "common.total": "الإجمالي",
    "common.required": "مطلوب",
    "common.optional": "اختياري",
    "common.pleaseSelect": "الرجاء الاختيار",
    "common.success": "تمت العملية بنجاح",
    "common.error": "حدث خطأ",
    "common.confirmDelete": "هل أنت متأكد من الحذف؟",
    "common.deleteWarning": "لا يمكن التراجع عن هذا الإجراء",
    "common.pageOf": "صفحة {page} من {total}",
    "common.showing": "عرض {from} إلى {to} من {total}",
    "common.language": "اللغة",
    "common.theme": "المظهر",
    "common.light": "فاتح",
    "common.dark": "داكن",
    "common.signOut": "تسجيل الخروج",
    "common.signIn": "تسجيل الدخول",
    "common.readMore": "اقرأ المزيد",
    "common.seeAll": "عرض الكل",
    "common.fromDate": "من تاريخ",
    "common.toDate": "إلى تاريخ",
    "common.print": "طباعة",
    "common.refresh": "تحديث",
    "common.pending": "قيد الانتظار",
    "common.approved": "موافق عليه",
    "common.rejected": "مرفوض",
    "common.cancelled": "ملغي",

    // Auth
    "auth.login": "تسجيل الدخول",
    "auth.logout": "تسجيل الخروج",
    "auth.email": "البريد الإلكتروني",
    "auth.password": "كلمة المرور",
    "auth.confirmPassword": "تأكيد كلمة المرور",
    "auth.rememberMe": "تذكرني",
    "auth.forgotPassword": "نسيت كلمة المرور؟",
    "auth.loginTitle": "مرحباً بعودتك",
    "auth.loginSubtitle": "سجل دخولك للوصول إلى لوحة التحكم",
    "auth.loginButton": "دخول",
    "auth.loginSuccess": "تم تسجيل الدخول بنجاح",
    "auth.invalidCredentials": "البريد الإلكتروني أو كلمة المرور غير صحيحة",
    "auth.accountLocked": "الحساب مقفل مؤقتاً. حاول مرة أخرى لاحقاً",
    "auth.register": "تسجيل جديد",
    "auth.createAccount": "إنشاء حساب",
    "auth.firstName": "الاسم الأول",
    "auth.lastName": "اسم العائلة",
    "auth.alreadyHaveAccount": "لديك حساب بالفعل؟",
    "auth.dontHaveAccount": "ليس لديك حساب؟",
    "auth.signUp": "إنشاء حساب",
    "auth.resetPassword": "إعادة تعيين كلمة المرور",
    "auth.sendResetLink": "إرسال رابط إعادة التعيين",

    // Navigation
    "nav.dashboard": "لوحة التحكم",
    "nav.employees": "الموظفون",
    "nav.departments": "الأقسام",
    "nav.positions": "المناصب",
    "nav.attendance": "الحضور",
    "nav.leave": "الإجازات",
    "nav.payroll": "الرواتب",
    "nav.recruitment": "التوظيف",
    "nav.documents": "الوثائق",
    "nav.reports": "التقارير",
    "nav.notifications": "الإشعارات",
    "nav.settings": "الإعدادات",
    "nav.profile": "الملف الشخصي",
    "nav.team": "الفريق",
    "nav.myRequests": "طلباتي",
    "nav.myPayslips": "كشوف رواتبي",
    "nav.myDocuments": "وثائقي",
    "nav.myAttendance": "حضوري",
    "nav.auditLogs": "سجلات التدقيق",

    // Dashboard
    "dashboard.welcome": "أهلاً بك",
    "dashboard.todayAttendance": "حضور اليوم",
    "dashboard.pendingRequests": "الطلبات المعلقة",
    "dashboard.upcomingHolidays": "العطل القادمة",
    "dashboard.birthdaysToday": "أعياد الميلاد اليوم",
    "dashboard.recentNotifications": "الإشعارات الحديثة",
    "dashboard.teamOverview": "نظرة عامة على الفريق",
    "dashboard.quickActions": "إجراءات سريعة",
    "dashboard.attendanceOverview": "نظرة عامة على الحضور",
    "dashboard.leaveRequests": "طلبات الإجازات",
    "dashboard.payrollSummary": "ملخص الرواتب",
    "dashboard.totalEmployees": "إجمالي الموظفين",
    "dashboard.presentToday": "الحاضرون اليوم",
    "dashboard.onLeave": "في إجازة",
    "dashboard.absent": "الغائبون",
    "dashboard.newHires": "التوظيفات الجديدة",
    "dashboard.monthlyPayroll": "رواتب الشهر",
    "dashboard.openPositions": "الوظائف الشاغرة",

    // Employees
    "employees.title": "إدارة الموظفين",
    "employees.add": "إضافة موظف",
    "employees.edit": "تعديل بيانات الموظف",
    "employees.view": "عرض الموظف",
    "employees.list": "قائمة الموظفين",
    "employees.code": "الرمز الوظيفي",
    "employees.fullName": "الاسم الكامل",
    "employees.fullNameAr": "الاسم بالعربية",
    "employees.fullNameEn": "الاسم بالإنجليزية",
    "employees.email": "البريد الإلكتروني",
    "employees.phone": "الهاتف",
    "employees.department": "القسم",
    "employees.position": "المنصب",
    "employees.manager": "المدير المباشر",
    "employees.hireDate": "تاريخ التعيين",
    "employees.contractType": "نوع العقد",
    "employees.status": "الحالة",
    "employees.basicSalary": "الراتب الأساسي",
    "employees.nationalId": "رقم الهوية",
    "employees.iqama": "الإقامة",
    "employees.passport": "جواز السفر",
    "employees.contract": "العقد",
    "employees.transfer": "نقل",
    "employees.promotion": "ترقية",
    "employees.termination": "إنهاء الخدمة",

    // Attendance
    "attendance.title": "الحضور والانصراف",
    "attendance.checkIn": "تسجيل الدخول",
    "attendance.checkOut": "تسجيل الخروج",
    "attendance.today": "اليوم",
    "attendance.thisWeek": "هذا الأسبوع",
    "attendance.thisMonth": "هذا الشهر",
    "attendance.history": "السجل",
    "attendance.status.present": "حاضر",
    "attendance.status.absent": "غائب",
    "attendance.status.late": "متأخر",
    "attendance.status.halfDay": "نصف يوم",
    "attendance.status.onLeave": "في إجازة",
    "attendance.status.holiday": "عطلة",
    "attendance.status.workFromHome": "عمل من المنزل",
    "attendance.workedHours": "ساعات العمل",
    "attendance.overtime": "العمل الإضافي",
    "attendance.lateMinutes": "دقائق التأخير",

    // Leave
    "leave.title": "إدارة الإجازات",
    "leave.request": "طلب إجازة",
    "leave.myRequests": "طلباتي",
    "leave.pending": "المعلقة",
    "leave.approved": "الموافق عليها",
    "leave.rejected": "المرفوضة",
    "leave.type": "نوع الإجازة",
    "leave.type.annual": "سنوية",
    "leave.type.sick": "مرضية",
    "leave.type.emergency": "طارئة",
    "leave.type.maternity": "أمومة",
    "leave.type.paternity": "أبوة",
    "leave.type.bereavement": "عزاء",
    "leave.type.unpaid": "بدون راتب",
    "leave.type.hajj": "حج",
    "leave.type.marriage": "زواج",
    "leave.type.study": "دراسية",
    "leave.type.compensatory": "تعويضية",
    "leave.startDate": "تاريخ البداية",
    "leave.endDate": "تاريخ النهاية",
    "leave.days": "الأيام",
    "leave.reason": "السبب",
    "leave.balance": "الرصيد",
    "leave.balance.annual": "رصيد الإجازة السنوية",
    "leave.balance.sick": "رصيد الإجازة المرضية",

    // Payroll
    "payroll.title": "الرواتب",
    "payroll.process": "معالجة الرواتب",
    "payroll.period": "الفترة",
    "payroll.basicSalary": "الراتب الأساسي",
    "payroll.allowances": "البدلات",
    "payroll.deductions": "الاستقطاعات",
    "payroll.netPay": "صافي الراتب",
    "payroll.grossPay": "إجمالي الراتب",
    "payroll.payslip": "كشف الراتب",
    "payroll.generatePayslip": "إصدار كشف الراتب",
    "payroll.approve": "اعتماد الرواتب",
    "payroll.processDate": "تاريخ المعالجة",
    "payroll.paymentDate": "تاريخ الدفع",
    "payroll.totalEarnings": "إجمالي المستحقات",
    "payroll.totalDeductions": "إجمالي الاستقطاعات",
    "payroll.loan": "سلفة",
    "payroll.overtime": "عمل إضافي",
    "payroll.bonus": "مكافأة",
    "payroll.salaryCertificate": "شهادة راتب",

    // Recruitment
    "recruitment.title": "التوظيف",
    "recruitment.jobOpenings": "الوظائف الشاغرة",
    "recruitment.candidates": "المرشحون",
    "recruitment.interviews": "المقابلات",
    "recruitment.offers": "عروض العمل",
    "recruitment.addJob": "إضافة وظيفة",
    "recruitment.addCandidate": "إضافة مرشح",
    "recruitment.scheduleInterview": "جدولة مقابلة",
    "recruitment.sendOffer": "إرسال عرض",
    "recruitment.status.new": "جديد",
    "recruitment.status.screening": "فرز",
    "recruitment.status.shortlisted": "قائمة قصيرة",
    "recruitment.status.interview": "مقابلة",
    "recruitment.status.offer": "عرض",
    "recruitment.status.hired": "تم التعيين",
    "recruitment.status.rejected": "مرفوض",

    // Documents
    "documents.title": "إدارة الوثائق",
    "documents.upload": "رفع وثيقة",
    "documents.expiry": "تاريخ الانتهاء",
    "documents.expiring": "قاربت على الانتهاء",
    "documents.expired": "منتهية",

    // Notifications
    "notifications.title": "الإشعارات",
    "notifications.markAllRead": "تحديد الكل كمقروء",
    "notifications.unread": "غير مقروءة",
    "notifications.empty": "لا توجد إشعارات",

    // Reports
    "reports.title": "التقارير",
    "reports.employees": "تقرير الموظفين",
    "reports.attendance": "تقرير الحضور",
    "reports.leave": "تقرير الإجازات",
    "reports.payroll": "تقرير الرواتب",
    "reports.recruitment": "تقرير التوظيف",

    // Settings
    "settings.title": "الإعدادات",
    "settings.general": "إعدادات عامة",
    "settings.company": "بيانات الشركة",
    "settings.roles": "الأدوار والصلاحيات",
    "settings.notifications": "إعدادات الإشعارات",
    "settings.email": "إعدادات البريد",
    "settings.security": "الأمان",
  },

  en: {
    "app.name": "HRMS Portal",
    "app.shortName": "HRMS",
    "app.tagline": "Human Resource Management System & Employee Self-Service",

    "common.welcome": "Welcome",
    "common.dashboard": "Dashboard",
    "common.profile": "Profile",
    "common.settings": "Settings",
    "common.notifications": "Notifications",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.export": "Export",
    "common.import": "Import",
    "common.add": "Add",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.view": "View",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.confirm": "Confirm",
    "common.close": "Close",
    "common.back": "Back",
    "common.next": "Next",
    "common.previous": "Previous",
    "common.submit": "Submit",
    "common.loading": "Loading...",
    "common.noData": "No data available",
    "common.actions": "Actions",
    "common.status": "Status",
    "common.date": "Date",
    "common.name": "Name",
    "common.code": "Code",
    "common.description": "Description",
    "common.active": "Active",
    "common.inactive": "Inactive",
    "common.yes": "Yes",
    "common.no": "No",
    "common.all": "All",
    "common.total": "Total",
    "common.required": "Required",
    "common.optional": "Optional",
    "common.pleaseSelect": "Please select",
    "common.success": "Operation completed successfully",
    "common.error": "An error occurred",
    "common.confirmDelete": "Are you sure you want to delete?",
    "common.deleteWarning": "This action cannot be undone",
    "common.pageOf": "Page {page} of {total}",
    "common.showing": "Showing {from} to {to} of {total}",
    "common.language": "Language",
    "common.theme": "Theme",
    "common.light": "Light",
    "common.dark": "Dark",
    "common.signOut": "Sign Out",
    "common.signIn": "Sign In",
    "common.readMore": "Read More",
    "common.seeAll": "See All",
    "common.fromDate": "From Date",
    "common.toDate": "To Date",
    "common.print": "Print",
    "common.refresh": "Refresh",
    "common.pending": "Pending",
    "common.approved": "Approved",
    "common.rejected": "Rejected",
    "common.cancelled": "Cancelled",

    "auth.login": "Login",
    "auth.logout": "Logout",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.confirmPassword": "Confirm Password",
    "auth.rememberMe": "Remember me",
    "auth.forgotPassword": "Forgot password?",
    "auth.loginTitle": "Welcome back",
    "auth.loginSubtitle": "Sign in to access your dashboard",
    "auth.loginButton": "Sign In",
    "auth.loginSuccess": "Logged in successfully",
    "auth.invalidCredentials": "Invalid email or password",
    "auth.accountLocked": "Account temporarily locked. Try again later.",
    "auth.register": "Register",
    "auth.createAccount": "Create Account",
    "auth.firstName": "First Name",
    "auth.lastName": "Last Name",
    "auth.alreadyHaveAccount": "Already have an account?",
    "auth.dontHaveAccount": "Don't have an account?",
    "auth.signUp": "Sign Up",
    "auth.resetPassword": "Reset Password",
    "auth.sendResetLink": "Send Reset Link",

    "nav.dashboard": "Dashboard",
    "nav.employees": "Employees",
    "nav.departments": "Departments",
    "nav.positions": "Positions",
    "nav.attendance": "Attendance",
    "nav.leave": "Leave",
    "nav.payroll": "Payroll",
    "nav.recruitment": "Recruitment",
    "nav.documents": "Documents",
    "nav.reports": "Reports",
    "nav.notifications": "Notifications",
    "nav.settings": "Settings",
    "nav.profile": "Profile",
    "nav.team": "Team",
    "nav.myRequests": "My Requests",
    "nav.myPayslips": "My Payslips",
    "nav.myDocuments": "My Documents",
    "nav.myAttendance": "My Attendance",
    "nav.auditLogs": "Audit Logs",

    "dashboard.welcome": "Welcome",
    "dashboard.todayAttendance": "Today's Attendance",
    "dashboard.pendingRequests": "Pending Requests",
    "dashboard.upcomingHolidays": "Upcoming Holidays",
    "dashboard.birthdaysToday": "Birthdays Today",
    "dashboard.recentNotifications": "Recent Notifications",
    "dashboard.teamOverview": "Team Overview",
    "dashboard.quickActions": "Quick Actions",
    "dashboard.attendanceOverview": "Attendance Overview",
    "dashboard.leaveRequests": "Leave Requests",
    "dashboard.payrollSummary": "Payroll Summary",
    "dashboard.totalEmployees": "Total Employees",
    "dashboard.presentToday": "Present Today",
    "dashboard.onLeave": "On Leave",
    "dashboard.absent": "Absent",
    "dashboard.newHires": "New Hires",
    "dashboard.monthlyPayroll": "Monthly Payroll",
    "dashboard.openPositions": "Open Positions",

    "employees.title": "Employee Management",
    "employees.add": "Add Employee",
    "employees.edit": "Edit Employee",
    "employees.view": "View Employee",
    "employees.list": "Employee List",
    "employees.code": "Employee Code",
    "employees.fullName": "Full Name",
    "employees.fullNameAr": "Name (Arabic)",
    "employees.fullNameEn": "Name (English)",
    "employees.email": "Email",
    "employees.phone": "Phone",
    "employees.department": "Department",
    "employees.position": "Position",
    "employees.manager": "Manager",
    "employees.hireDate": "Hire Date",
    "employees.contractType": "Contract Type",
    "employees.status": "Status",
    "employees.basicSalary": "Basic Salary",
    "employees.nationalId": "National ID",
    "employees.iqama": "Iqama",
    "employees.passport": "Passport",
    "employees.contract": "Contract",
    "employees.transfer": "Transfer",
    "employees.promotion": "Promotion",
    "employees.termination": "Termination",

    "attendance.title": "Attendance",
    "attendance.checkIn": "Check In",
    "attendance.checkOut": "Check Out",
    "attendance.today": "Today",
    "attendance.thisWeek": "This Week",
    "attendance.thisMonth": "This Month",
    "attendance.history": "History",
    "attendance.status.present": "Present",
    "attendance.status.absent": "Absent",
    "attendance.status.late": "Late",
    "attendance.status.halfDay": "Half Day",
    "attendance.status.onLeave": "On Leave",
    "attendance.status.holiday": "Holiday",
    "attendance.status.workFromHome": "Work From Home",
    "attendance.workedHours": "Worked Hours",
    "attendance.overtime": "Overtime",
    "attendance.lateMinutes": "Late Minutes",

    "leave.title": "Leave Management",
    "leave.request": "Request Leave",
    "leave.myRequests": "My Requests",
    "leave.pending": "Pending",
    "leave.approved": "Approved",
    "leave.rejected": "Rejected",
    "leave.type": "Leave Type",
    "leave.type.annual": "Annual",
    "leave.type.sick": "Sick",
    "leave.type.emergency": "Emergency",
    "leave.type.maternity": "Maternity",
    "leave.type.paternity": "Paternity",
    "leave.type.bereavement": "Bereavement",
    "leave.type.unpaid": "Unpaid",
    "leave.type.hajj": "Hajj",
    "leave.type.marriage": "Marriage",
    "leave.type.study": "Study",
    "leave.type.compensatory": "Compensatory",
    "leave.startDate": "Start Date",
    "leave.endDate": "End Date",
    "leave.days": "Days",
    "leave.reason": "Reason",
    "leave.balance": "Balance",
    "leave.balance.annual": "Annual Leave Balance",
    "leave.balance.sick": "Sick Leave Balance",

    "payroll.title": "Payroll",
    "payroll.process": "Process Payroll",
    "payroll.period": "Period",
    "payroll.basicSalary": "Basic Salary",
    "payroll.allowances": "Allowances",
    "payroll.deductions": "Deductions",
    "payroll.netPay": "Net Pay",
    "payroll.grossPay": "Gross Pay",
    "payroll.payslip": "Payslip",
    "payroll.generatePayslip": "Generate Payslip",
    "payroll.approve": "Approve Payroll",
    "payroll.processDate": "Process Date",
    "payroll.paymentDate": "Payment Date",
    "payroll.totalEarnings": "Total Earnings",
    "payroll.totalDeductions": "Total Deductions",
    "payroll.loan": "Loan",
    "payroll.overtime": "Overtime",
    "payroll.bonus": "Bonus",
    "payroll.salaryCertificate": "Salary Certificate",

    "recruitment.title": "Recruitment",
    "recruitment.jobOpenings": "Job Openings",
    "recruitment.candidates": "Candidates",
    "recruitment.interviews": "Interviews",
    "recruitment.offers": "Offer Letters",
    "recruitment.addJob": "Add Job",
    "recruitment.addCandidate": "Add Candidate",
    "recruitment.scheduleInterview": "Schedule Interview",
    "recruitment.sendOffer": "Send Offer",
    "recruitment.status.new": "New",
    "recruitment.status.screening": "Screening",
    "recruitment.status.shortlisted": "Shortlisted",
    "recruitment.status.interview": "Interview",
    "recruitment.status.offer": "Offer",
    "recruitment.status.hired": "Hired",
    "recruitment.status.rejected": "Rejected",

    "documents.title": "Documents Management",
    "documents.upload": "Upload Document",
    "documents.expiry": "Expiry Date",
    "documents.expiring": "Expiring Soon",
    "documents.expired": "Expired",

    "notifications.title": "Notifications",
    "notifications.markAllRead": "Mark all as read",
    "notifications.unread": "Unread",
    "notifications.empty": "No notifications",

    "reports.title": "Reports",
    "reports.employees": "Employees Report",
    "reports.attendance": "Attendance Report",
    "reports.leave": "Leave Report",
    "reports.payroll": "Payroll Report",
    "reports.recruitment": "Recruitment Report",

    "settings.title": "Settings",
    "settings.general": "General Settings",
    "settings.company": "Company Info",
    "settings.roles": "Roles & Permissions",
    "settings.notifications": "Notification Settings",
    "settings.email": "Email Settings",
    "settings.security": "Security",
  },
};

export type TranslationKey = keyof typeof translations.ar;

export function translate(locale: Locale, key: string, params?: Record<string, string | number>): string {
  const dict = translations[locale] || translations.ar;
  let text = (dict as any)[key] || translations.en[key as TranslationKey] || key;

  if (params) {
    Object.entries(params).forEach(([k, v]) => {
      text = text.replace(`{${k}}`, String(v));
    });
  }
  return text;
}

export function getDirection(locale: Locale): "rtl" | "ltr" {
  return locale === "ar" ? "rtl" : "ltr";
}
